#cloud-config
ssh_pwauth: no
users:
  - name: admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC7JiAQRpz0c7x84UST7xEc3NrliyD2B4eg5nobQ/liH ditry@study"