---
all:
  hosts:
    nexus-01:
      ansible_host: "{{ lookup('env','NEXUS') | ansible.utils.ipv4 }}"
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: admin